### ISSUE TITLE
custom launch API parameter

### ISSUE THREAD

**Issue by acidlemon** [acidlemon/mirage#3]
like this:

```yaml
parameter:
  - name: branch
    env: GIT_BRANCH
    rule: "[0-9a-z-]{32}"

  - name: nick
    env: NICK
    rule: "[0-9A-Za-z]{10}"
```

usage:

```
curl http://docker.example.com/api/launch \
    -d subdomain=foo          \
    -d image=myapp:latest   \
    -d branch=feature/foo     \
    -d nick=acidlemon
```

RUN script will receive environment variables `GIT_BRANCH` and `NICK`.
